- include/spatialindex/SpatialIndex.h
- src/capi/Index.cc
- src/mvrtree/MVRTree.cc
- src/mvrtree/MVRTree.h
- src/rtree/RTree.cc
- src/rtree/RTree.h
- src/tprtree/TPRTree.cc
- src/tprtree/TPRTree.h
Each RTree variant also needs to be able to flush its header to disk on
request so that we can successfully reopen indices.
> Add a flush function to each index type

- src/mvrtree/MVRTree.cc
There was a revert of some attempted lock upgrades that accidentally
switched the pthread calls. This only triggered when compiled under
Linux and worked fine on OS X.
> Fix the locking calls in MVRTree.cc

- src/rtree/Node.cc
Fix Incorrect R*-tree reinsertion implementation
===
I'm pretty sure that libspatialindex has an incorrect R*-tree implementation
related to the structure optimizations. I'm still working on groking the
algorithm completely so I may be missing a detail.
First I've listed code snippets from the paper's algorithms as well as from
the source to libspatialindex. The end of this writeup describes the bug as
I understand it with a discussion the fix.
The R*-tree paper's "Algorithm Reinsert"
---
This is on page 327 on the copy I'm reading (which is the one linked
from Wikipedia).
http://dbs.mathematik.uni-marburg.de/publications/myPapers/1990/BKSS90.pdf
<pre>
Algorithm Reinsert
RI1 - For all M+l entries of a node N, compute the distance
between the centers of their rectangles and the center
of …
> Fix Node::reinsertData selection criteria

- src/rtree/Index.cc
- src/rtree/Index.h
- src/rtree/Node.cc
This forces an MBR calculation when reinserting entries during an
R*-tree update that would have otherwise required a node split.
Fixes #58
> Fix adjustTree during R*-tree reinserts

- src/rtree/Index.cc
This uses the correct new shape for detecting containment of the new MBR
when adjusting the tree after a split during insertion.
Fixes #57
> Fix Index::adjustTree/4

- src/spatialindex/Region.cc
This flips the logic so that we correctly identify if two regions share
a value for a dimension.
Fixes #55
> Fix Region::touchesRegion

- src/rtree/Node.cc
This fixes a bug where we were not updating the root node's MBR when a
condenseTree operation removed a child entry. While harmless from an
operational point of view it causes isIndexValid to fail.
> Update the root MBR during condenseTree

- CMakeLists.txt
-Upped the minimum version so WIN32 will not be defined
-Disabled std=c++98 if we're on cygwin, because it caused srand48 and mktemp to fail. I'm not sure you need this option at all though.
Tested it with the python rtree library.
> Made a few changes so it would compile on Cygwin.

- src/rtree/Index.cc
With R*Tree splits there's no guarantee that the newly added node ends
up in the n2 node passed to adjustTree. As such we have to test both n1
and n2 for containment.
> Fix RTree::Index::adjustTree

- src/rtree/Leaf.cc
- src/rtree/Leaf.h
- src/rtree/RTree.cc
If a leaf has multiple entries for the same identifier we have to check
that we're deleting the correct MBR.
> Fix RTree deletions

- configure.ac
The user may want to provide its own set of optimization flags, and
therefore forcing -O2 should not be done.
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
> configure.ac: do not force -O2

- src/capi/sidx_api.cc
When filling the array, it iterates through `nDimension` elements, but only allocates `nLeafSizes[k]` entries. This causes out-of-bounds access when dimensions are greater than leafs.
This causes a crash in `geopandas/tests/test_sindex.py::TestSeriesSindex::test_point`, though only on 32-bit for some reason (or possibly it's just more likely there.)
> Fix array allocation in Index_GetLeaves.

- CMakeLists.txt
- ChangeLog
- include/spatialindex/capi/sidx_config.h
- test/gtest/CMakeLists.txt
I wanted to compile the library using Visual Studio 2017. Therefore i added all necessary adjustments to source code and cmake configuration. Everything is wrapped in specific conditions for MSVC with a version greater or equal 1900.
> Cmake support for 'Visual Studio 15 2017 [Win64]' generator

- src/rtree/RTree.h
Stay consistent in the use of tabs as opposed to spaces.
> Use tabs as opposed to spaces for consistency.

- src/rtree/Index.cc
This PR correct intend to correct this QGIS issue : https://issues.qgis.org/issues/19579
Computed area is sometimes equal to infinity for all children, so this PR forces the method findLeastEnlargement to return always a valid child.
> Correct findLeastEnlargement method to always return a correct value

- test/gtest/gtest-1.7.0/CMakeLists.txt
Allows MSVC builds without having to manually change any settings
> Default gtest to use shared run-time lib

- src/tools/Tools.cc
GNU warning about `mktemp` function:
> Warning: Between the time the pathname is constructed and the file is created another process might have created a file with the same name using mktemp, leading to a possible security hole. The implementation generates names which can hardly be predicted, but when opening the file you should use the O_EXCL flag. Using mkstemp is a safe way to avoid this problem.
https://www.gnu.org/software/libc/manual/html_node/Temporary-Files.html
> Change 'mktemp' to 'mkstemp' in 'Tools'

- test/gtest/gtest-1.7.0/scripts/fuse_gtest_files.py
In some systems, the default python version is 3.
> Set default python version to python2 in gtest

- include/spatialindex/capi/sidx_api.h
Replace `function()` with `function(void)` to conform with the C standard.
> Fix strict prototype warnings in C API

- include/spatialindex/capi/sidx_api.h
- src/capi/sidx_api.cc
- test/gtest/sidx_api_test.h
For some reason, those endpoints were not exposed in C-API previously. Would be great to add'em, right?
> Exposes Index_Contains_id, Index_Contains_obj endpoints in C-API

- test/gtest/gtest-1.7.0/include/gtest/gtest.h
> Ignore gtest signed/unsigned warning in gcc

- include/spatialindex/MovingRegion.h
- src/mvrtree/MVRTree.h
- src/rtree/BulkLoader.h
- src/rtree/RTree.cc
- src/rtree/RTree.h
- src/spatialindex/MovingRegion.cc
- src/tprtree/TPRTree.h
- test/mvrtree/Exhaustive.cc
- test/rtree/Exhaustive.cc
std::binary_function was deprecated in c++11 and removed in c++17. If you want to keep the old behaviour I would suggest adding the functional include and also force older c++ version in CMakeLists.
> Removed deprecated binary_function functions.

- include/spatialindex/capi/sidx_api.h
closes https://github.com/libspatialindex/libspatialindex/issues/181
> Linux and Macos: fix unknown type name 'size_t' in C API

- CMakeLists.txt
closes https://github.com/libspatialindex/libspatialindex/issues/177
> Allow building static libs

- CMakeLists.txt
The user is unable to override CMAKE_BUILD_TYPE since version 1.9.1 and
https://github.com/libspatialindex/libspatialindex/commit/e3bcccf38d9f100b59ccf29f7e1cfa174969decd
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> CMakeLists.txt: fix CMAKE_BUILD_TYPE

- include/spatialindex/capi/sidx_config.h
closes https://github.com/libspatialindex/libspatialindex/issues/179
> Fix C API for Visual Studio

- test/gtest/gtest-1.10.0/src/gtest-filepath.cc
This PR addresses an error from #192 for the axp build with Linux Clang 5:
```
...
Scanning dependencies of target gtest
[ 94%] Building CXX object test/gtest/gtest-1.10.0/CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from /home/vsts/work/1/s/test/gtest/gtest-1.10.0/src/gtest-all.cc:43:
/home/vsts/work/1/s/test/gtest/gtest-1.10.0/src/gtest-filepath.cc:104:12: error: use of undeclared identifier '_POSIX_PATH_MAX'; did you mean '_PC_PATH_MAX'?
char cwd[GTEST_PATH_MAX_ + 1] = { '\0' };
^~~~~~~~~~~~~~~
_PC_PATH_MAX
/home/vsts/work/1/s/test/gtest/gtest-1.10.0/src/gtest-filepath.cc:55:26: note: expanded from macro 'GTEST_PATH_MAX_'
^
/usr/include/x86_64-linux-gnu/bits/confname.h:34:5: note: '_PC_PATH_MAX' declared here
_PC_PATH_MAX,
^
1 error generated. …
```
> GTest: Workaround Clang 5.0 axp issue with define _POSIX_PATH_MAX 256

- CMakeLists.txt
- src/CMakeLists.txt
- test/CMakeLists.txt
- test/gtest/CMakeLists.txt
This PR does the minimal amount of changes from #191, including:
* Consistent formatting of CMakeLists.txt files using 'cmakelint'
* Use top project() to set VERSION and LANGUAGE to CXX
* Use CMAKE_CXX_STANDARD_REQUIRED=ON, CMAKE_CXX_EXTENSIONS=OFF
* SIDX_COMMON_CXX_FLAGS was previously ignored -- so use it for GNU and Clang
* Use CMake target names spatialindex and spatialindex_c rather than variables
* Disable unused <libname>_EXPORTS (based on DEFINE_SYMBOL)
* Remove set(CMAKE_COLOR_MAKEFILE ON)
* Remove unused APPS_CPP_DEPENDENCIES cached variable
* Remove old note about hack with add_definitions("-fPIC")
* CMAKE_MODULE_PATH was not used, remove logic
> CMake: modern formatting and features

- scripts/azp/linux.yml
- scripts/azp/osx.yml
- scripts/azp/win.yml
This PR allows more verbose azp builds, to show commands used to build objects, which helps to see flags and options used with compilers.
C compilers are not required for libspatialindex, but are required for GTest, so add CC to job matrix for consistency.
The osx build had used an in-source build, which are generally not recommended.
And last remark, the Linux builds don't require build configuration (`-C`) for build and test steps, as these use the default "Unix Makefiles" generator.
> azp: verbose builds, specify CC (for GTest), osx outsource build

- CMakeLists.txt
- libspatialindexConfig.cmake.in
It seems that a derivative CMake project that use `find_package(libspatialindex)` do not work as expected:
```
...
CMake Error at /tmp/lib/cmake/libspatialindex/libspatialindexConfig.cmake:11 (message):
File or directory referenced by variable SIDX_LIB_DIR does not exist !
```
and sure enough, SIDX_LIB_DIR wasn't set to anything. This PR does several things:
* Add missing PATH_VARS: LIB_INSTALL_DIR
* Remove unused SYSCONFIG_INSTALL_DIR
* Remove other unused PDAL_* vars
* Change INCLUDE_INSTALL_DIR to SIDX_INCLUDE_DIR value
* SIDX_LIBRARIES must use constant library target names (this only matters to Windows builds)
These changes are not captured thru CI yet, however I have some postinstall tests that I'll see how to fit into the azp workflow.
> CMake: fix find_package(libspatialindex)

- scripts/azp/linux.yml
- scripts/azp/osx.yml
- scripts/azp/win.yml
- test/postinstall/test_c/CMakeLists.txt
- test/postinstall/test_c/test_c.c
- test/postinstall/test_cc/CMakeLists.txt
- test/postinstall/test_cc/test_cc.cc
- test/postinstall/test_cmake.bat
- test/postinstall/test_cmake.sh
There's a few things going on here:
* Install of libspatilindex is done (rather than just building/testing)
* CMake's `find_package(libspatialindex)` is tested to build and C and C++ applications, using dynamic linking
* The installed C API is tested to build C programs (it appears this has been broken in the past)
For the Linux build, this is only tested along side the C++11 build. For OSX and Windows, "Dist" now does "Dist and install", followed by "Post-install test".
The test C and C++ apps do trivial things with libspatialindex, and essentially make sure the application linking is done as expected. There is no author/copyright info in these source files, since they are trivial. However, if this consistency is preferred, I can add it to the source files. (And yes, I'm the original …
> CMake/azp: Test install and run post-install tests for demo apps

- .gitignore
- CMakeLists.txt
- src/libspatialindex.pc.in
The [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/) was lost when the autotools setup was removed, however some users may want to use this interface. It's simple to install from the CMake setup.
One of the issues with the previous pkg-config file is that it had:
```
Cflags: -I${includedir}/spatialindex
```
which is impossible to use with a C header `#include <spatialindex/capi/sidx_api.h>`. It is changed/fixed in this PR.
Some post-install tests (similar to #200) will be added when ready.
> pkg-config: restore functionality (via CMake), change Cflags

- scripts/azp/linux.yml
- scripts/azp/osx.yml
- test/postinstall/test_c/Makefile
- test/postinstall/test_cc/Makefile
- test/postinstall/test_pkg-config.sh
This PR adds to post-install tests for demo apps (#200) by testing installed pkg-config files (#201).
> azp: Run post-install tests for demo apps with pkg-config

- scripts/azp/linux.yml
- scripts/azp/osx.yml
Just realised that YAML lists are `key: [0, 1]`, and not `key: 0, 1` or `key: 0 1`. (Update: they shouldn't be lists)
osx was missing some `set -e` options to catch potential errors.
<s>Checking to see if repetition for build step can be compacted.</s>
Fix linux test PATH for build dirnames.
> azp: fix linux test PATH, always use 'set -e' for osx

- INSTALL
2 notes:
* About section `Compiling For Multiple Architectures` I'm not sure it still needed or not.
* About the `Copyright (C)` section. I changed the range of dates to a simple one. But the previous one had some gap like 2003 is not in the copyright dates. I'm not sure it was missed or not and the new changes will be a problem about this.
> Update the INSTALL document #211

- .gitignore
- docs/source/conf.py
- docs/source/index.rst
Fixes #215 
* Builds Doxygen when `make html` is run in the ReadTheDocs environment.
* Installs at `/doxygen/` in the built HTML
* Makes the Class Documentation link on the homepage relative
Tested locally via `READTHEDOCS=True make html`, not sure what more I can do than that.
> Add doxygen docs to ReadTheDocs builds

- README.rst
This is a small change to just the main README.rst. Our sysadmins want the docs to match the release number before installing this library.
> Update README.rst Revision and Date to match other docs

- .github/workflows/dependabot.yml
Add a Dependabot configuration that checks once a week if the GitHub Actions are still using the latest version. If not, it opens a PR to update them.
It will actually open very few PRs, since we only have major versions specified (like v3), so only on a major v4 release it will update and open a PR.
See [Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot).
> Add Dependabot configuration for GitHub Actions updates

- include/spatialindex/Ball.h
- include/spatialindex/SpatialIndex.h
- src/CMakeLists.txt
- src/spatialindex/Ball.cc
- test/gtest/gtest-1.10.0/src/gtest-death-test.cc
Hello!
I've written a Ball Shape that can be used in intersection and containsWhat queries to find all objects in the tree within a certain distance of a point.
A function in [test/gtest/gtest-1.10.0/src/gtest-death-test.cc](https://github.com/libspatialindex/libspatialindex/compare/master...Plaba:libspatialindex:master?expand=1#diff-75b9ab41264f983c418b1bc3eb3ad15a436e7a3a168838b88aca7a2f88c89177) was raising -Werror=maybe-uninitialized on compilation and breaking builds, so I fixed that as well.
> Added Ball Shape for point neighborhood queries

- src/storagemanager/DiskStorageManager.cc
- src/storagemanager/DiskStorageManager.h
- Fix #236
Caveat: I'm not in the least familiar with your codebase, I only use the python package `rtree`.
I only build the lib and checked that it compiles fine and ran `ninja test` / `ctest` which appears to run only a single test.
* https://github.com/Toblerity/rtree/issues/247
**Edit**: pretty sure storeByteArray will still try to write to it...
> Fix #236 - Open read-only and don't flush if index exists and overwrite is false

- CMakeLists.txt
- src/CMakeLists.txt
- src/mvrtree/Index.cc
- src/mvrtree/MVRTree.cc
- src/mvrtree/PointerPoolNode.h
- src/rtree/BulkLoader.cc
- src/rtree/PointerPoolNode.h
- src/rtree/RTree.cc
- src/spatialindex/MovingRegion.cc
- src/spatialindex/Region.cc
- src/tprtree/Index.cc
- src/tprtree/Node.cc
- src/tprtree/PointerPoolNode.h
- src/tprtree/TPRTree.cc
The library would often pick up `NDEBUG` defines from default CFLAG/CXXFLAG values depending on whether or not the BUILD_TYPE has been set. This changes the entire behavior to require an explicit opt-in by the user choosing a debug build type from CMake and guarding with a `SIDX_DEBUG` define.
> No longer key debug print output based on NDEBUG system define

- test/CMakeLists.txt
- test/cleanup-test-output.sh
- test/geometry/test1/run
- test/index-tests.sh
- test/mvrtree/test1/run
- test/mvrtree/test2/run
- test/rtree/test1/run
- test/rtree/test2/run
- test/rtree/test3/run
- test/rtree/test4/run
- test/tprtree/test1/run
- test/tprtree/test2/run
pushd/popd are bashisms, use cd & cd -
allows me to run 2.0.0 release tests fine on OpenBSD where sh is pdksh.
> test: don't require bash, use plain posix shell

- .codespell.ignore
- .codespellrc
- ChangeLog
- docs/doxygen/doxygen.conf
- src/capi/sidx_api.cc
- src/mvrtree/MVRTree.cc
- src/mvrtree/MVRTree.h
- src/mvrtree/Node.cc
- src/mvrtree/Statistics.cc
- src/rtree/Node.cc
- src/rtree/RTree.h
- src/spatialindex/MovingRegion.cc
- src/spatialindex/Region.cc
- src/spatialindex/TimeRegion.cc
- src/tools/Tools.cc
- src/tprtree/Node.cc
- src/tprtree/TPRTree.cc
- src/tprtree/TPRTree.h
- test/gtest/gtest-1.14.0/include/gtest/gtest-printers.h
- test/mvrtree/MVRTreeLoad.cc
- test/mvrtree/MVRTreeQuery.cc
- test/rtree/RTreeBulkLoad.cc
- test/rtree/RTreeLoad.cc
- test/rtree/RTreeQuery.cc
- test/tprtree/TPRTreeLoad.cc
- test/tprtree/TPRTreeQuery.cc
This PR adds a configuration for [codespell](https://github.com/codespell-project/codespell), and fixes a handful of typos.
> Add configuration for codespell and correct typos

- src/rtree/BulkLoader.cc
This fixes some memory leaks which my previous commit introduced.
ASAN is still showing one leak when running the tests:
```
Direct leak of 120 byte(s) in 1 object(s) allocated from:
#0 0x7f8b634f9e68 in operator new(unsigned long) (/usr/lib/gcc/x86_64-pc-linux-gnu/14/libasan.so.8+0xf9e68)
#1 0x7f8b631df4df in SpatialIndex::RTree::ExternalSorter::getNextRecord() /home/freddie/Programming/libspatialindex/src/rtree/BulkLoader.cc:297
#2 0x7f8b631e0ad2 in SpatialIndex::RTree::BulkLoader::createLevel(SpatialIndex::RTree::RTree*, std::shared_ptr<SpatialIndex::RTree::ExternalSorter>, unsigned int, unsigned int, unsigned int, unsigned int, std::shared_ptr<SpatialIndex::RTree::ExternalSorter>, unsigned int, unsigned int) /home/freddie/Programming/libspatialindex/src/rtree/BulkLoader.cc:422
#3 …
```
> Fix a memory leak introduced in the previous commit.

- src/rtree/RTree.cc
- src/rtree/RTree.h
Here we take advantage of the fact that we know some data types.  In particular, we know what `getShape` of `Data` will do (create a new instance of its `Region`).  Thus, we can just pass this region in directly.  This saves a new/delete pair.  The improvement from this is around ~5%.
> Reduce overhead in kNN queries

- include/spatialindex/capi/Index.h
- include/spatialindex/capi/sidx_api.h
- src/capi/Index.cc
- src/capi/sidx_api.cc
- test/gtest/sidx_api_test.h
This is intended to gather feedback.  I've mocked up a bulk insert API which takes a set of array pointers as opposed to a function pointer.  This requires some very minor refactoring but nothing too major.  Feedback on the overall approach would be appreciated.  I've tried to make the API reasonably flexible by including strides which should allow most reasonable data structures (AoS or SoA) to be directly ingested.
Assuming everything checks out I'll wire everything up for Python RTree.
> Add an alternative bulk-insert API

- src/capi/sidx_api.cc
We currently fail to clear the result count in the bulk APIs.  This PR resolves this issue (and probably warrants a point release).
> Ensure the bulk APIs always set nr.

- include/spatialindex/capi/LeafQuery.h
LeafQueryResult should be defined before LeafQuery, so that the std::vector<LeafQueryResult> member in LeafQuery does not cause a warning about forward declared class destruction from the inline ~LeafQuery definition.
> Fix compilation warning on newer gcc
